### ISSUE TITLE
Question: is "tabs" permission necessary for what we currently have?

### ISSUE THREAD

**Issue by ykdojo** [ykdojo/OpenStream#10]
https://github.com/ykdojo/OpenStream/blob/e4d89e6eec8545db4d4022e49a447168d68e1858/manifest.json#L6

**Comment by ervinCodes** [comment]
Hey YK, I think with what we currently have, "tabs" is not necessary since we have not yet built it to the point where we are using it freely.  I think we can remove it for now, and as the project progresses to the point we need further access then we can add it back on.

**Comment by ykdojo** [comment]
Removing it for now sounds good!
