### ISSUE TITLE
Task: Project Principles

### ISSUE THREAD

**Issue by teerth17** [ykdojo/OpenStream#16]
## Project Task

- [ ] **Share Some Principles of This Project We Care About**
  - ![Screenshot 2024-01-20 161539](https://github.com/ykdojo/OpenStream/assets/76660982/3ce75b42-41fc-400b-a1fb-5be2f04c03c7)

**Comment by ykdojo** [comment]
Shared:
![Image](https://github.com/ykdojo/OpenStream/assets/1811651/3923114a-cc89-4bf6-a840-55b5f2cae896)

Original link: https://twitter.com/ykdojo/status/1748714336519078297
