### ISSUE TITLE
Make these issues/tasks more descriptive (now: make them shorter)

### ISSUE THREAD

**Issue by ykdojo** [ykdojo/OpenStream#18]

**Comment by teerth17** [comment]
@ykdojo Done. Have a look

**Comment by ykdojo** [comment]
Thank you. It's definitely better.

> Task: Investigate- technically possible to ? Separate File Recording (Screen & Webcam), Max Resolution Inquiry, Simultaneous Audio Capture"
^This one's too long though.

Also, we shouldn't have Task: as part of the issue titles as it gets pretty repetitive
