### ISSUE TITLE
Create a "Hello World" extension with Plasmo

### ISSUE THREAD

**Issue by ykdojo** [ykdojo/OpenStream#20]
#9

**Comment by ykdojo** [comment]
Based on #9, we've decided to go with Plasmo.

Looks like their GitHub repo has documentation on how to get started with it: https://github.com/PlasmoHQ/plasmo?tab=readme-ov-file#usage

Going through it, creating a Hello World extension with it, then documenting how to do it would be great.

**Comment by Devanshukoli** [comment]
Hey, I was just wondering, why should we create *Hello world* extension? Can't we direct jump on our main **Quest**?

**Comment by ykdojo** [comment]
Hope this clarifies it: https://github.com/users/ykdojo/projects/3/views/1?pane=issue&itemId=50701954

**Comment by omar-shahid** [comment]
I'm working on this one
