### ISSUE TITLE
Decide what framework to use in conjunction with Plasmo

### ISSUE THREAD

**Issue by ykdojo** [ykdojo/OpenStream#26]
Now that we've decided to use Plasmo on #9, we'll most likely need to use one of:

- React
- Svelte
- Vue.js

As they specifically mention these frameworks on their website. Which one should we go with?

![Image](https://github.com/ykdojo/OpenStream/assets/1811651/b83ffdeb-380f-4759-8a95-9c5974a5287a)

**Comment by omar-shahid** [comment]
Couldn't find other framework support, however, they have first-class support for React... https://docs.plasmo.com/framework#development-server

![image](https://github.com/ykdojo/OpenStream/assets/40920737/41055dc6-d1e3-495f-a8b6-3aa4936050cd)
![image](https://github.com/ykdojo/OpenStream/assets/40920737/23ed2dfe-b2d5-4ee6-b7e0-1e759a8f0b41)

**Comment by omar-shahid** [comment]
Yep, this confirms they have 1st class support for React. But they have optional support for Vue and svelte

![image](https://github.com/ykdojo/OpenStream/assets/40920737/ebf1c1b1-d4e2-4a06-ac30-9c957e339099)

**Comment by ykdojo** [comment]
Thank you @omar-shahid! React might be the way to go, then.
