### ISSUE TITLE
Review the PR for adding issue templates (note: this should be reviewed again)

### ISSUE THREAD

**Issue by ykdojo** [ykdojo/OpenStream#27]
#4

**Comment by mehta-avi** [comment]
To further improve:

BugReport.md:
> Severity Level: A severity level tag (e.g., low, medium, high) to help streamline bugs and also ensuring that developers can effectively prioritize which bugs to work on.

Question.md:
> Categories: By categorizing the questions, it makes it easy to sort them.

**Comment by ykdojo** [comment]
@mehta-avi feel free to add your review on #4

**Comment by mehta-avi** [comment]
@ykdojo done!

**Comment by ykdojo** [comment]
Note: this should be reviewed again.

**Comment by mehta-avi** [comment]
@ykdojo reviewed again and everything lgtm.
